Attempting to fix RSS Script

diff --git a/.github/workflows/retype-action.yml b/.github/workflows/retype-action.yml
--- a/.github/workflows/retype-action.yml
+++ b/.github/workflows/retype-action.yml
@@ -108,10 +108,10 @@ jobs:
           node-version: 16
 
       - name: Install dependencies
-        run: npm install rss markdown-it feedparser deep-equal glob
+        run: npm install rss markdown-it feedparser-promised deep-equal glob
 
       - name: Generate RSS Feed
-        run: node .github/scripts/generate-rss.js
+        run: node .github/scripts/generate-rss.js || echo "An error occurred. See the stack trace above for more details."
 
       - name: Commit and push if it's necessary
         run: |
